### ISSUE TITLE
Hard-code references to postgresql-9.4 might break compatibility with Stretch

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/umap_old_ynh#13]
Hellow,

I see that there are some hard-coded reference to postgresql 9.4 in the code of this package : 

e.g. : 
https://github.com/YunoHost-Apps/umap_ynh/blob/master/scripts/install#L53

Since Stretch now has postgresql 9.6, this might break the installation or other functionalities of this app on Stretch / Yunohost 3.x

**Comment by madtibo** [comment]
Hello,
If there is a problem using postgresql-9.6 with umap, it would always be possible to install postgresql-9.4 using the PGDG repository.
```
$ cat /etc/apt/sources.list.d/postgresql.org.list
deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
```

**Comment by zicmama** [comment]
Trying to install umap on stretch Yunohost. I have an error:

yunohost app install https://github.com/YunoHost-Apps/umap_ynh.git

```
Warning: 'yunohost app checkurl' is deprecated and will be removed in the future
Warning: Packagers /!\ 'app checkurl' is deprecated ! Please use 'app register-url' instead !
Warning: E: Unable to locate package postgresql-server-dev-9.4
Warning: E: Couldn't find any package by glob 'postgresql-server-dev-9.4'
Warning: E: Couldn't find any package by regex 'postgresql-server-dev-9.4'
Warning: E: Unable to locate package python3.4-dev
Warning: E: Couldn't find any package by glob 'python3.4-dev'
Warning: E: Couldn't find any package by regex 'python3.4-dev'
Warning: ERROR:  role "root" does not exist
Warning: ERROR:  role "root" does not exist
Warning: dropdb: database removal failed: ERROR:  database "umap" does not exist
Warning: ERROR:  extension "postgis" does not exist
Warning: ERROR:  role "umap" does not exist
Warning: ERROR:  role "root" does not exist
Warning: Failed to disable unit: No such file or directory
Warning: /etc/uwsgi/apps-enabled wasn't deleted because it doesn't exist.
Warning: /opt/umap wasn't deleted because it doesn't exist.
Warning: /etc/nginx/conf.d/map.madeinzion.org.d/umap.conf wasn't deleted because it doesn't exist.
Warning: userdel: user 'umap' does not exist
Success! The SSOwat configuration has been generated
Error: Installation failed
```
How could I resolve it?

**Comment by madtibo** [comment]
@zicmama Can you try using the PGDG package?

Instructions from https://wiki.postgresql.org/wiki/Apt#Quickstart are:

Add the PGDG source list:
```
echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' > /etc/apt/sources.list.d/postgresql.org.list
apt install wget ca-certificates
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
apt update
```

Then you can install the postgresql-server-dev-9.4 package:
```
apt install postgresql-server-dev-9.4
```

**Comment by anmol26s** [comment]
@madtibo 
Why not use postgresql 9.6 ?
You have to remove the 9.4 and just install Postgresql here: https://github.com/YunoHost-Apps/umap_ynh/blob/master/scripts/install#L53

**Comment by zicmama** [comment]
A agree, It would be better to use 9.6 in install script as yunohost is now based on stretch...

**Comment by madtibo** [comment]
@anmol26s ok, I though umap had a strong dependency to postgresql 9.4. If the 9.6 version can be used, it will be much simpler.

**Comment by zicmama** [comment]
I think we should give a try using postgresql 9.6.
Fork and modify install script to use 9.6, use it for my yunohost install so we could merge if it works ;)

Anyone knows why "dev" package is required?

**Comment by yohanboniface** [comment]
> ok, I though umap had a strong dependency to postgresql 9.4.

It does not :)
You use 9.6 or even 10 without any issue.

> Anyone knows why "dev" package is required?

AFAIK, it's needed by python-psycopg2.

**Comment by zicmama** [comment]
I've fork and change installed packages (postgresql-server-dev-9.6 & python3.5-dev)
But there is still errors.

> Warning: 'yunohost app checkurl' is deprecated and will be removed in the future
> Warning: Packagers /!\ 'app checkurl' is deprecated ! Please use 'app register-url' instead !
> Extracting templates from packages: 100%
> Warning: /usr/share/yunohost/helpers.d/psql: line 101: $3: unbound variable
> Warning: ERROR:  role "root" does not exist
> Warning: ERROR:  role "root" does not exist
> Warning: dropdb: database removal failed: ERROR:  database "umap" does not exist
> Warning: ERROR:  extension "postgis" does not exist
> Warning: ERROR:  role "umap" does not exist
> Warning: ERROR:  role "root" does not exist
> Warning: Failed to disable unit: No such file or directory
> Warning: /etc/uwsgi/apps-enabled wasn't deleted because it doesn't exist.
> Warning: /etc/nginx/conf.d/apps.madeinzion.org.d/umap.conf wasn't deleted because it doesn't exist.
> Success! The SSOwat configuration has been generated
> Error: Installation failed
> 

Anyone understand why is this going wrong?

**Comment by madtibo** [comment]
I'm looking into it and will propose a PR.

**Comment by madtibo** [comment]
@zicmama the MR has been merged. Tell me if you experience the same problem.

**Comment by zicmama** [comment]
Thanks @madtibo ;)
My previous problem was from yunohost bad upgrade... Solved with a "dist-upgrade"
now, when I try to install umap_ynh, I still have an error ;(

Reported here https://paste.yunohost.org/raw/bezifacahe
Not much informative??

**Comment by madtibo** [comment]
OK, just a filename that has been changed!
I created a new PR.

**Comment by zicmama** [comment]
Nope. https://paste.yunohost.org/raw/inoduhomes

**Comment by madtibo** [comment]
ok, the install script is using deprecated functions.
Corrective PR done.

I used the wordpress package as example ([old](https://github.com/YunoHost-Apps/wordpress_ynh/blob/27fecc14f7eed3d855aaa1581037a9c4f3bf9077/scripts/install) and [new](https://github.com/YunoHost-Apps/wordpress_ynh/blob/master/scripts/install) code). Please check if I am doing the right thing.

**Comment by zicmama** [comment]
https://paste.yunohost.org/raw/podogefedo

**Comment by madtibo** [comment]
@zicmama wait, wait, the PR has not been merged yet  :-)

**Comment by zicmama** [comment]
> @zicmama wait, wait, the PR has not been merged yet :-)

OK. Thanks so much

**Comment by madtibo** [comment]
@zicmama long time no news, does it mean the issue is resolved?  
:-)

**Comment by decentral1se** [comment]
Is this still relevant? I see now that 9.6 is being used.

https://github.com/YunoHost-Apps/umap_ynh/blob/master/scripts/install#L71

**Comment by alexAubin** [comment]
Cheers ;P
